# Generated by Django 6.0.3 on 2026-03-26 09:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[("admin", "Admin"), ("researcher", "Researcher")],
                max_length=50,
                unique=True,
            ),
        ),
    ]
