services:
  db:
    image: postgres:17
    container_name: research_registry_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - research_registry_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: research_registry_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - research_registry_net

  web:
    build:
      context: ./backend
    container_name: research_registry_web
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    ports:
      - "8000:8000"
    networks:
      research_registry_net:
        aliases:
          - web
    depends_on:
      - db
      - rabbitmq

  worker_default:
    build: ./backend
    container_name: research_registry_worker_default
    command: celery -A research_registry worker -l info -Q default
    restart: unless-stopped
    networks:
      - research_registry_net
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq

  worker_exports:
    build: ./backend
    container_name: research_registry_worker_exports
    command: celery -A research_registry worker -l info -Q exports
    restart: unless-stopped
    networks:
      - research_registry_net
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq

volumes:
  postgres_data:
  media:


networks:
  research_registry_net:
    external: true
